/**
 * Juxtapo
 * Front End Tools: JavaScript Library
 * http://juxtapo.net/
 * 
 * Version 1.2.2
 * 
 * Copyright (c) 2010 Dave Taylor (@davetayls), http://the-taylors.org
 * This source code is subject to terms and conditions of the New BSD License.
 * A copy of the license can be found in the license.txt file at the root of this distribution.
 * If you cannot locate the New BSD License, please send an email to dave@the-taylors.org.
 * By using this source code in any fashion, you are agreeing to be bound by the terms of the New BSD License.
 * You must not remove this notice, or any other, from this software.
 * 
 * If you find this software useful please support it's development by 
 * donating at http://github.com/davetayls/juxtapo.
 *
 */

var juxtapo;
(function(d){var e="",a=function(){juxtapo.coreJsUrl()&&juxtapo.utils.requireResource(juxtapo.coreJsUrl()+"juxtapo.css")},c=function(){juxtapo.container=document.createElement("div");d(juxtapo.container).attr("id","juxtapo-container");d("body").append(juxtapo.container)},b=function(){for(var f in juxtapo.plg)if(juxtapo.plg.hasOwnProperty(f)){var j=juxtapo.plg[f];typeof j.init==="function"&&j.init()}},g=function(){var f=juxtapo.utils.getQuery("status");juxtapo.currentStatus=f?f:juxtapo.statuses.pause},i=
function(){d(juxtapo).trigger("_initComplete")},h=function(){d(juxtapo).trigger("_initConfig")};juxtapo={version:"1.2.2",statuses:{off:0,play:1,pause:2},designViews:{hidden:0,semiTransparent:1,opaque:2},container:null,controller:null,currentDesignView:0,currentStatus:2,designVisible:false,plg:{add:function(f,j){this[f]||(this[f]=new juxtapo.Plugin(j))}},globalSettings:{},coreJsUrl:function(){if(e===""){e=juxtapo.utils.getJsLocation(/juxtapo(\.dev)*\.js/);if(!juxtapo.utils.isAbsoluteUrl(e)){e=juxtapo.utils.resolveAbsoluteUrl(window.location.href,
e);juxtapo.eh.logInfo("coreJsUrl: "+e)}}return e},init:function(){a();h();g();if(juxtapo.currentStatus!==juxtapo.statuses.off){c();juxtapo.templates.init();juxtapo.control.init()}juxtapo.eh.init();juxtapo.thumbs.init();b();i()},addPlugins:function(f){for(var j=0;j<f.length;j+=1){var k=juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),f[j]);document.write('<script type="text/javascript" src="'+k+'"><\/script>')}},addTemplate:function(f,j,k){if(f instanceof juxtapo.templates.TemplateItem){juxtapo.templates.collection.push(f);
return f}else{if(typeof f==="string")f=[f];f=new juxtapo.templates.TemplateItem(j,f,k);juxtapo.templates.collection.push(f);return f}},setDefaultStyles:function(f){juxtapo.templates.TemplateItem.defaultStyles=f},initConfig:function(f){d(juxtapo).bind("_initConfig",f)},initComplete:function(f){d(juxtapo).bind("_initComplete",f)}};juxtapo.onBody_KeyDown=function(f){var j;if(window.event)j=window.event.keyCode;else if(f)j=f.which;else return true;juxtapo.eh.logInfo("keycode is: "+j);if(f.ctrlKey&&(j===
79||j===39)){juxtapo.templates.forward();juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&(j===85||j===37)){juxtapo.templates.back();juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===38){juxtapo.templates.change(true);juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===40){juxtapo.templates.change(false);juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===32){juxtapo.control.toggle();juxtapo.utils.preventDefaultEventAction(f);
return false}var k=f.shiftKey?1:25;if(f.ctrlKey&&j===73){juxtapo.templates.nudge("top",k);juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===76){juxtapo.templates.nudge("right",k);juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===75){juxtapo.templates.nudge("bottom",k);juxtapo.utils.preventDefaultEventAction(f);return false}if(f.ctrlKey&&j===74){juxtapo.templates.nudge("left",k);juxtapo.utils.preventDefaultEventAction(f);return false}return true}})(jQuery,
this);if(window.addEventListener)window.addEventListener("load",juxtapo.init,false);else window.attachEvent&&window.attachEvent("onload",juxtapo.init);
(function(d){var e=null;juxtapo.eh={errors:"",hasError:false,initCompleted:false,dropDown:function(){return e},init:function(){e=new juxtapo.ui.DropDown({style:{height:"300px",width:"450px"}});e.text("e");e.title("Error logger");d(e.contents).addClass("juxtapo-errorBox");juxtapo.eh.renderErrors();this.initCompleted=true},logInfo:function(a){juxtapo.eh.errors='<li class="juxtapo-info">['+juxtapo.utils.date.toShortTimeString(new Date)+"] "+a+"</li>"+juxtapo.eh.errors;juxtapo.eh.renderErrors();return juxtapo.eh.errors},
logError:function(a){if(typeof a==="string")juxtapo.eh.errors='<li class="juxtapo-error">'+a+"</li>"+juxtapo.eh.errors;else if(typeof a==="object")juxtapo.eh.errors='<li class="juxtapo-error">[object]'+juxtapo.utils.objectToStructureString(a)+"</li>"+juxtapo.eh.errors;else juxtapo.eh.errors+='<li class="juxtapo-error">'+a.toString()+"</li>";juxtapo.eh.hasError=true;juxtapo.eh.renderErrors();return juxtapo.eh.errors},renderErrors:function(){if(e){e.contentHtml("<ul>"+juxtapo.eh.errors+"</ul>");d(e.controller).removeClass("juxtapo-eh-error");
if(juxtapo.eh.hasError===true){d(e.controller).addClass("juxtapo-eh-error");e.text("!")}else e.text("e")}return true}};juxtapo.eh.Exception=function(a,c){this.message=a;this.trace=c}})(jQuery);
(function(d){juxtapo.control={controller:document.createElement("div"),initCompleted:false,secondsBeforeRefresh:2.5,timerId:-1,init:function(){d(this.controller).attr({"class":"juxtapo-btn",id:"juxtapo-controller",title:"Automatically refresh the page"}).click(this.toggle).appendTo(juxtapo.container);juxtapo.currentStatus===juxtapo.statuses.pause?juxtapo.control.pause():juxtapo.control.play();this.initCompleted=true},play:function(){juxtapo.currentStatus=juxtapo.statuses.play;this.controller.innerHTML=
"|&nbsp;|";this.timerId=setTimeout("juxtapo.control.reload()",this.secondsBeforeRefresh*1E3);return juxtapo.currentStatus},pause:function(){juxtapo.currentStatus=juxtapo.statuses.pause;this.controller.innerHTML=">";clearTimeout(this.timerId);return juxtapo.currentStatus},reload:function(){if(juxtapo.currentStatus===juxtapo.statuses.play){var e=juxtapo.utils.getQuery("jxurl");e=e?unescape(e):location.href;var a=e.indexOf("?")>-1?"&":"?";e=e+a+"jxurl="+escape(e)+"&r="+(new Date).toString()+"&status="+
juxtapo.currentStatus+"&design="+juxtapo.designVisible+"&v="+d(document).scrollTop()+"&dv="+juxtapo.currentDesignView+"&di="+juxtapo.templates.selectedTemplateIndex;location.href=e}},toggle:function(){return juxtapo.currentStatus===juxtapo.statuses.pause?juxtapo.control.play():juxtapo.control.pause()}}})(jQuery);
(function(d){var e=null,a=function(b,g,i){d(juxtapo).trigger("_overlayImagePositionChanged",[b,g,i])},c=function(){d(juxtapo.templates.overlayButton).removeClass("juxtapo-overlayTransparent").removeClass("juxtapo-overlaySemiTrans").removeClass("juxtapo-overlayOpaque")};juxtapo.templates={collection:[],selectedTemplateIndex:0,back:function(){if(juxtapo.currentDesignView===juxtapo.designViews.hidden)juxtapo.templates.show();else juxtapo.currentDesignView===juxtapo.designViews.semiTransparent?juxtapo.templates.hide():
juxtapo.templates.semiTransparent()},change:function(b){if(b){b=juxtapo.templates.selectedTemplateIndex-1;if(b<0)b=juxtapo.templates.collection.length-1}else{b=juxtapo.templates.selectedTemplateIndex+1;if(b>juxtapo.templates.collection.length-1)b=0}juxtapo.templates.changeTo(b)},changeTo:function(b){var g=null;if(typeof b==="undefined")return false;else if(typeof b==="object")g=b;else if(typeof b==="number"&&b<juxtapo.templates.collection.length){juxtapo.templates.selectedTemplateIndex=b;g=juxtapo.templates.collection[b]}if(g){b=
d.extend({},juxtapo.templates.TemplateItem.defaultStyles,g.settings.style);d("#design").attr("src",g.getImageSrc()).css(b)}},selectedTemplateItem:function(){return juxtapo.templates.collection[juxtapo.templates.selectedTemplateIndex]},overlayImageElement:function(b){if(typeof b!=="undefined")e=b;else e||(e=document.getElementById("design"));return e},filterBySearch:function(b){var g=null;if(b==="")d("#juxtapo-thumbs-container .juxtapo-thumb").show();else{g=this.search(b);d("#juxtapo-thumbs-container .juxtapo-thumb").hide();
for(var i=0;i<g.designs.length;i+=1)g.designs[i].thumbnail.show()}return{q:b,designs:g}},forward:function(){if(juxtapo.currentDesignView===juxtapo.designViews.hidden)juxtapo.templates.semiTransparent();else juxtapo.currentDesignView===juxtapo.designViews.semiTransparent?juxtapo.templates.show():juxtapo.templates.hide()},getAll:function(){return juxtapo.templates.collection},getTemplateFromUrl:function(b){b=b.toLowerCase();for(var g=0;g<juxtapo.templates.collection.length;g+=1)for(var i=juxtapo.templates.collection[g],
h=0;h<i.paths.length;h+=1){var f=i.paths[h].toLowerCase();if(b.juxtapoContains(f)){juxtapo.templates.selectedTemplawteIndex=g;return i}}return juxtapo.templates.collection[0]},hide:function(){d("#design").css("display","none");juxtapo.designVisible=false;juxtapo.currentDesignView=juxtapo.designViews.hidden;c();d(this.overlayButton).addClass("juxtapo-overlayTransparent");return juxtapo.currentDesignView},init:function(){d('<img id="design" src="noimage.jpg" alt="design image" />').appendTo("body").css({display:"none"});
juxtapo.utils.getQuery("di")!==null?juxtapo.templates.changeTo(parseInt(juxtapo.utils.getQuery("di"),10)):juxtapo.templates.changeTo(juxtapo.templates.getTemplateFromUrl(location.href));d(document).keydown(juxtapo.onBody_KeyDown);juxtapo.templates.overlayButton=document.createElement("div");d(juxtapo.templates.overlayButton).attr("class","juxtapo-btn");juxtapo.templates.overlayButton.onclick=juxtapo.templates.toggle;juxtapo.templates.overlayButton.innerHTML="OVERLAY";juxtapo.templates.overlayButton.title=
"Toggle visibility of the overlay";juxtapo.container.appendChild(juxtapo.templates.overlayButton);var b=juxtapo.utils.getQuery("design");if(b!==null)juxtapo.designVisible=b;b=juxtapo.utils.getQuery("dv");if(!b)b=juxtapo.currentDesignView;if(b!==null){b=parseInt(b,10);if(b===juxtapo.designViews.hidden)juxtapo.templates.hide();else b===juxtapo.designViews.semiTransparent?juxtapo.templates.semiTransparent():juxtapo.templates.show()}(b=juxtapo.utils.getQuery("v"))&&d(document).scrollTop(b)},nudge:function(b,
g){if(b==="")return false;if(typeof g==="undefined")g=1;var i=this.overlayImageElement(),h=d(i),f="margin-left";if(i.style.left.indexOf("%")<0)f=h.css("right")!=="auto"?"right":"left";i={offSet:h.offset(),position:h.position()};switch(b){case "top":f=parseInt(h.css("top"),10);h.css("top",f-g);break;case "right":b=parseInt(h.css(f),10);f!=="right"?h.css(f,b+g):h.css(f,b-g);break;case "bottom":f=parseInt(h.css("top"),10);h.css("top",f+g);break;case "left":b=parseInt(h.css(f),10);f!=="right"?h.css(f,
b-g):h.css(f,b+g);break}g={offSet:h.offset(),position:h.position()};a(h.get(0),i,g);return this},search:function(b){var g={designs:[],indexes:[]};if(b!==""){b=b.toLowerCase();for(var i=0;i<juxtapo.templates.collection.length;i+=1){var h=juxtapo.templates.collection[i];if(h.imageUrl.toLowerCase().indexOf(b)>-1||h.paths[0].toLowerCase().indexOf(b)>-1){g.designs.push(h);g.indexes.push(i)}}}return g},show:function(){d("#design").css({display:"block",opacity:"1"});juxtapo.designVisible=true;juxtapo.currentDesignView=
juxtapo.designViews.opaque;c();d(this.overlayButton).addClass("juxtapo-overlayOpaque");return juxtapo.currentDesignView},semiTransparent:function(){d("#design").css({display:"block",opacity:"0.5"});juxtapo.designVisible=true;juxtapo.currentDesignView=juxtapo.designViews.semiTransparent;c();d(this.overlayButton).addClass("juxtapo-overlaySemiTrans");return juxtapo.currentDesignView},toggle:function(){juxtapo.templates.forward()},overlayImagePositionChanged:function(b){d(juxtapo).bind("_overlayImagePositionChanged",
b)}};juxtapo.templates.TemplateItem=function(b,g,i){this._init(b,g,i)};juxtapo.templates.TemplateItem.prototype={imageUrl:"",paths:[],settings:{data:{},style:{}},thumbnail:null,_init:function(b,g,i){var h=this;h.imageUrl=b;if(typeof g==="object"&&g.constructor===Array)h.paths=g;else if(typeof g==="string")h.paths=[g];else throw new juxtapo.eh.Exception("Cannot initiate this TemplateItem, valid paths can be a string or array of strings");h.settings=d.extend({},juxtapo.templates.TemplateItem.prototype.settings,
i);h.setUiThumbnail=function(f){h.thumbnail=f;d(h).trigger("_thumbnailSet");return h};h.thumbnailSet=function(f){d(h).bind("_thumbnailSet",f);return h}},getImageSrc:function(){return juxtapo.utils.isRelativeUrl(this.imageUrl)?juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),this.imageUrl):this.imageUrl}};juxtapo.templates.TemplateItem.defaultStyles={position:"absolute","z-index":"2000",top:"0px",left:"50%","margin-left":"-550px"}})(jQuery);
(function(d){var e;juxtapo.utils={createCookie:function(a,c,b){if(b){var g=new Date;g.setTime(g.getTime()+b*24*60*60*1E3);b="; expires="+g.toGMTString()}else b="";document.cookie=a+"="+c+b+"; path=/";return true},date:{toShortTimeString:function(a){return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+":"+a.getMilliseconds()}},eraseCookie:function(a){e.createCookie(a,"",-1);return true},getQuery:function(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b+=1){var g=c[b].split("=");
if(g[0]===a)return g[1]}return null},getJsLocation:function(a){if(typeof a==="string")a=new RegExp(a.toLowerCase());for(var c=document.getElementsByTagName("script"),b=0;b<c.length;b+=1){var g=c[b],i=g.src.substring(g.src.lastIndexOf("/")+1).toLowerCase();if(a.test(i))return g.src.substring(0,g.src.lastIndexOf("/")+1)}return null},getKeyCombination:function(a){a=a.split("+");for(var c={ctrl:false,keyCode:-1,shift:false},b=0;b<a.length;b+=1){var g=a[b].toLowerCase();if(isNaN(parseInt(g,10))){c.shift=
c.shift||g==="shift";c.ctrl=c.ctrl||g==="ctrl"}else c.keyCode=parseInt(g,10)}return c},htmlFromTemplate:function(a,c){for(var b in c)if(c.hasOwnProperty(b))a=a.replace(new RegExp("\\${"+b+"}","g"),c[b]);return a},isAbsoluteUrl:function(a){a=a.toLowerCase();if(a.substr(0,7)==="http://")return true;if(a.substr(0,8)==="file:///")return true;if(a.substr(0,6)==="ftp://")return true;return false},isRelativeUrl:function(a){a=a.toLowerCase();if(a.substr(0,2)==="~/")return true;if(a.substr(0,3)==="../")return true;
if(a.substr(0,2)==="./")return true;return false},isStaticUrl:function(a){a=a.toLowerCase();if(a.substr(0,7)==="file://")return true;if(a.substr(0,6)==="ftp://")return true;if(a.substr(1,1)===":")return true;return false},objectToStructureString:function(a,c,b){if(a===window)return"window";if(typeof c==="undefined")c="";if(typeof b==="undefined")b=0;var g="";for(var i in a)if(!(a[i]instanceof Function))if(typeof a[i]==="object"){if(b<3)g+="<li>"+i+":<br />"+juxtapo.utils.objectToStructureString(a[i],
c+"&nbsp;&nbsp;&nbsp;&nbsp;",b+1)+"</li>"}else g+="<li>"+i+":"+a[i]+"</li>";b="";for(var h in a)if(a[h]instanceof Function)b+="<li>"+h+"</li>";a="";if(g!=="")a+="<li>Properties : <ul>"+g+"</ul></li>";if(b!=="")a+="<br />"+c+"<li>Functions : <ul>"+b+"</ul></li>";return"<ul>"+a+"</ul>"},preventDefaultEventAction:function(a){a.preventDefault();a.keyCode=0;a.which=0},readCookie:function(a){a=a+"=";for(var c=document.cookie.split(";"),b=0;b<c.length;b+=1){for(var g=c[b];g.charAt(0)===" ";)g=g.substring(1,
g.length);if(g.indexOf(a)===0)return g.substring(a.length,g.length)}return null},requireResource:function(a,c){var b=document.getElementsByTagName("head")[0],g=false,i=false;if(a.substr(a.lastIndexOf("."))===".css"){var h=document.createElement("link");h.setAttribute("rel","stylesheet");h.setAttribute("type","text/css");h.setAttribute("href",a);b.appendChild(h);return h}else if(a.substr(a.lastIndexOf("."))===".js"){var f=document.createElement("script");f.type="text/javascript";if(typeof c!=="undefined"){f.onreadystatechange=
function(){if(this.readyState==="complete"&&!g){i=g=true;typeof c!=="undefined"&&c.call(f,a)}};f.onload=function(){if(!g){i=g=true;typeof c!=="undefined"&&c.call(f,a)}}}f.src=a;d(f).appendTo(b);return f}return null},resolveAbsoluteUrl:function(a,c){if(c.substr(0,1)==="/")return a.substring(0,a.indexOf("/",a.indexOf("//")+2))+c;else if(e.isAbsoluteUrl(c))return c;else{a=a;for(a=a.substring(0,a.lastIndexOf("/"));/^\.\./.test(c);){a=a.substring(0,a.lastIndexOf("/"));c=c.substring(3)}c=e.String.ltrim(c,
"/");return a+"/"+c}},String:{contains:function(a,c){return a.indexOf(c)>-1},ltrim:function(a,c){c=c||"\\s";return a.replace(new RegExp("^["+c+"]+","g"),"")},replace:function(a,c,b){return a.replace(new RegExp("["+c+"]","g"),b)},right:function(a,c){if(c<=0)return"";else if(c>String(a).length)return a;else{var b=String(a).length;return String(a).substring(b,b-c)}},rtrim:function(a,c){c=c||"\\s";return a.replace(new RegExp("["+c+"]+$","g"),"")},trim:function(a,c){return e.String.ltrim(e.String.rtrim(a,
c),c)}}};e=juxtapo.utils;String.prototype.juxtapoContains=function(a){return juxtapo.utils.String.contains(this,a)}})(jQuery);juxtapo.ui={};
(function(d){var e=null;juxtapo.ui.DropDown=function(a){this._init(a)};juxtapo.ui.DropDown.prototype={afterOpen:null,beforeOpen:null,controller:null,contents:null,expanded:null,settings:{cssClass:"",style:{height:"auto",width:"905px"}},_init:function(a){this.settings=d.extend({},this.settings,a);this.render();var c=this;d(document).bind("keydown",function(b){if(c.expanded&&b.which===27){c.show(false);return false}})},contentHtml:function(a){if(typeof a==="undefined")return d(this.contents).html();
else d(this.contents).html(a)},render:function(){var a=this;this.controller=document.createElement("div");d(this.controller).attr("class","juxtapo-dropDown");this.controller.onclick=function(){a.toggleShow()};juxtapo.container.appendChild(this.controller);this.contents=document.createElement("div");d(this.contents).attr("class","juxtapo-lightBox").css(this.settings.style);document.getElementsByTagName("body")[0].appendChild(this.contents)},show:function(a){if(typeof a==="undefined")a=true;if(a&&!this.expanded){if(e){e.show(false);
e=null}this.beforeOpen&&this.beforeOpen();d(this.contents).show();d(this.controller).addClass("juxtapo-btn-open");this.expanded=true;e=this;this.afterOpen&&this.afterOpen()}else if(!a){d(this.contents).hide();d(this.controller).removeClass("juxtapo-btn-open");this.expanded=false}return this.expanded},text:function(a){if(typeof a==="undefined")return d(this.controller).html();else d(this.controller).html(a);return this},title:function(a){if(typeof a==="undefined")return d(this.controller).attr("title");
else d(this.controller).attr("title",a);return this},toggleShow:function(){return this.show(!this.expanded)}}})(jQuery);
(function(d){juxtapo.ui.Thumbnail=function(e,a){this._init(e,a)};juxtapo.ui.Thumbnail.prototype={container:null,designTemplate:null,settings:{},thumbnailHtmlTemplate:'  <a href="${href}" class="juxtapo-thumb-lnk">    <span class="juxtapo-thumb-img">      <img height="220" alt="design image" src="${imageSrc}">    </span>  </a>  <span class="juxtapo-thumb-caption">    <a href="${href}" tabindex="-1">      ${caption}    </a>  </span>',_init:function(e,a){var c=this;c.settings=d.extend({},this.settings,
a);c.designTemplate=e;c.container=d('<div class="juxtapo-thumb" />').append(juxtapo.utils.htmlFromTemplate(this.getThumbnailHtmlTemplate(),this.getThumbnailData())).get(0);e.setUiThumbnail(c);c.show=function(b){if(typeof b==="undefined")b=true;b?d(c.container).show():d(c.container).hide()}},getImageSrc:function(){return this.designTemplate.getImageSrc()},getLinkHref:function(e){return juxtapo.utils.isRelativeUrl(e)?juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),e):e},getThumbnailData:function(){return{caption:this.designTemplate.paths[0],
href:this.getLinkHref(this.designTemplate.paths[0]),imageSrc:this.getImageSrc()}},getThumbnailHtmlTemplate:function(){return this.thumbnailHtmlTemplate}}})(jQuery);
(function(d){juxtapo.ui.Toolbar=function(e){this._init(e)};juxtapo.ui.Toolbar.prototype={_init:function(e){var a=this;this.settings=d.extend({},this.settings,e);this.toolbar$=d('<div class="juxtapo-ui-toolbar juxtapo-cc" class="juxtapo-cc" />');this.toolbarLeft$=d('<div class="juxtapo-ui-toolbarL juxtapo-cc" />').appendTo(a.toolbar$);this.toolbarRight$=d('<div class="juxtapo-ui-toolbarR juxtapo-cc" />').appendTo(a.toolbar$);this.appendTo=function(c){a.toolbar$.appendTo(c);return a};this.appendLeft=
function(c){a.toolbarLeft$.append(c);return a};this.appendRight=function(c){a.toolbarRight$.append(c);return a}},settings:{}}})(jQuery);
(function(d){juxtapo.ui.ToolBtn=function(e){this._init(e)};juxtapo.ui.ToolBtn.prototype={container:null,contents:null,settings:{},_init:function(e,a){var c=this;c.settings=d.extend({},this.settings,a);c.contents=d('<span class="juxtapo-toolbtn-contents" />').get(0);c.container=d('<a class="juxtapo-toolbtn" />').append(c.contents).get(0);c.click=function(b){d(c.container).click(b);return c};c.show=function(){d(c.container).show();return c};c.text=function(b){d(c.contents).html(b);return c}}}})(jQuery);
(function(d){var e,a=null,c=new juxtapo.ui.Toolbar,b=d('<input id="juxtapo-searchDesigns" type="text" title="Search" />'),g=d('<label><span class="label-text">Search:</span></label>').append(b),i=d('<div id="juxtapo-thumbs-container" />');juxtapo.thumbs={rendered:false,dropDown:function(){return a},init:function(){e=juxtapo.thumbs;a=new juxtapo.ui.DropDown;a.text("+");a.title("View template thumbnails");var h=this;a.beforeOpen=function(){h.rendered||h.renderThumbs()};a.afterOpen=function(){d("#juxtapo-searchDesigns").focus()}},
appendToToolbarLeft:function(h){c.toolbarLeft$.append(h);return e},appendToToolbarRight:function(h){c.toolbarRight$.append(h);return e},renderThumbs:function(){juxtapo.eh.logInfo("thumbs rendering");var h=parseInt(d(window).height(),10)-50;d(a.contents).append(c.toolbar$).append(i);c.toolbarLeft$.append(g);i.css("height",h-39+"px");for(h=0;h<juxtapo.templates.collection.length;h+=1){var f=new juxtapo.ui.Thumbnail(juxtapo.templates.collection[h]);i.append(f.container)}b.keyup(this.searchKeyup);this.rendered=
true;d(juxtapo.thumbs).trigger("_thumbsRendered")},searchKeyup:function(){var h=d(this).val();juxtapo.templates.filterBySearch(h)},thumbsContainer:function(){return i.get(0)},thumbsRendered:function(h){d(juxtapo.thumbs).bind("_thumbsRendered",h)}}})(jQuery);
(function(){var d=null;juxtapo.initComplete(function(){d=new juxtapo.ui.DropDown({style:{width:"300px"}});d.text("?");d.title("Juxtapo help and information");var e="";e="<h4>juxtapo version: "+juxtapo.version+', <a href="http://juxtapo.net">website</a></h4><h4>Keyboard Shortcuts</h4><table width="100%"><tr><td>Move Left</td><td>Ctrl+J [+shift for nudge]</td></tr><tr><td>Move Right</td><td>Ctrl+L [+shift for nudge]</td></tr><tr><td>Move Up</td><td>Ctrl+I [+shift for nudge]</td></tr><tr><td>Move Down</td><td>Ctrl+K [+shift for nudge]</td></tr><tr><td>Previous Design</td><td>Ctrl+Up</td></tr><tr><td>Next Design</td><td>Ctrl+Down</td></tr><tr><td>Transparency Back</td><td>Ctrl+U</td></tr><tr><td>Transparency Forward</td><td>Ctrl+O</td></tr><tr><td>Auto Refresh Play/Stop</td><td>Ctrl+Space</td></tr></table><h4>Documention</h4><ul><li><a href="'+juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),
"../docs/index.html")+'">juxtapo API documentation</a></ul>';d.contentHtml(e)})})(jQuery);
(function(d){juxtapo.Plugin=function(e){if(typeof e==="object")e=e;else if(typeof e==="function"){e=e.call(this);if(typeof e!=="object")e={}}else if(typeof e==="undefined")e={};else throw new juxtapo.eh.Exception("A plugin cannot be instantiated with a "+typeof e);d.extend(this,{},e)};juxtapo.Plugin.prototype={init:function(){if(this.initComplete)return true;if(typeof this._init==="function")try{this._init.call(this)}catch(e){juxtapo.eh.logError(e);return false}this.initComplete=true;this.onInitCompleted();
return true},initComplete:false,initCompleted:function(e){d(this).bind("_initCompleted",e)},onInitCompleted:function(){d(this).trigger("_initCompleted")}}})(jQuery);
